### ISSUE TITLE
Rasperry Pi OS Lite 32bit

### ISSUE THREAD

**Issue by luigidavia** [geekworm-com/x735-v2.5#11]
HI, I have updated yesterday my raspberry Pi and now I have these errors when remoting in via SSH:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Can't connect to pigpio at localhost(8888)

Did you start the pigpio daemon? E.g. sudo pigpiod

Did you specify the correct Pi host/port in the environment
variables PIGPIO_ADDR/PIGPIO_PORT?
E.g. export PIGPIO_ADDR=soft, export PIGPIO_PORT=8888

Did you specify the correct Pi host/port in the
pigpio.pi() function? E.g. pigpio.pi('soft', 8888)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Traceback (most recent call last):
  File "/home/pi/x735-v2.5/pwm_fan_control.py", line 8, in <module>
    pwm.set_mode(servo, pigpio.OUTPUT)
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1376, in set_mode
    return _u2i(_pigpio_command(self.sl, _PI_CMD_MODES, gpio, mode))
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1025, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
AttributeError: 'NoneType' object has no attribute 'send'

when I change directory to x735v2.5 and run the python3 pwm_fan_control.py command, I get the same error and when I run the 
python3 read_fan_speed.py the speed is always stuck at 0.

any help is highly appreciated!

**Comment by marnow955** [comment]
I had the same problem. I found a solution in this pigpio issue: https://github.com/joan2937/pigpio/issues/203.
To make read_fan_speed.py work:
- find systemctl service file by running:
systemctl show -P FragmentPath pigpiod.service
- change ExecStart to:
ExecStart=/usr/bin/pigpiod -l -n 127.0.0.1
- reboot the system
